Fixed grey lines
opencodeiiita/Opencode-Collaborative-20 pull request #385
Opened 2020-02-12 15:52 UTC by sarthakm21

__369__ 

Fixes #369 

#### Short description of what this resolves:

Removed the grey lines

#### Changes proposed in this pull request and/or Screenshots of changes:

-
![grey](https://user-images.githubusercontent.com/58396189/74351861-b64f8f80-4ddd-11ea-9fc9-2422ecb2ce74.PNG)

-
-

2020-02-12 17:36 UTC, Jigar3 commented
live-link?

2020-02-12 18:15 UTC, sarthakm21 commented
Sir I am not getting an option to share the live link for any branch other than the master branch

2020-02-12 18:16 UTC, sarthakm21 commented
Although the only changes that I made are removing those lines and the change is visible in the screenshot

2020-02-13 07:20 UTC, Jigar3 commented
Try netlify. In GitHub you can't create live link on any branch other than master

2020-02-13 07:27 UTC, sarthakm21 commented
https://amazing-minsky-b9a3ff.netlify.com/

2020-02-13 08:05 UTC, Jigar3 commented
The section looks really short, it could be nice if you could add more content in the about Section

2020-02-13 08:17 UTC, sarthakm21 commented
@Jigar3 Please look at the link again and tell me if I should add more content..

2020-02-13 08:19 UTC, Jigar3 commented on index.html
> +              It is organised anually by Geekhaven, the technical society of Indian Institute of Information Technology, Allahabad. It aims at giving
*annually

2020-02-13 08:20 UTC, Jigar3 requested changes
Check for spelling errors

2020-02-13 08:24 UTC, sarthakm21 commented
Done!!

2020-02-13 08:25 UTC, merged