Add a preloader to the website
opencodeiiita/Opencode-Collaborative-20 pull request #397
Opened 2020-02-14 04:11 UTC by sggts04

__11__ 

Fixes #11 

#### Short description of what this resolves:
Adds a preloader to the website.

#### Changes proposed in this pull request and/or Screenshots of changes:
Live Link: https://shreyasgupta.in/Opencode-Collaborative-20/

2020-02-14 04:39 UTC, Jigar3 commented
The preloader background color doesn't match with the overall color scheme of the website. Use some other color

2020-02-14 04:42 UTC, sggts04 commented
@Jigar3 done, I have made it match the website background, i.e. white.

2020-02-14 04:47 UTC, Jigar3 commented
Doesn't reflect in the live link

2020-02-14 04:48 UTC, sggts04 commented
https://shreyasgupta.in/Opencode-Collaborative-20/ 
Try Shift+F5 maybe?
This is how its looking on my side
![image](https://user-images.githubusercontent.com/20678047/74502384-578c3200-4f13-11ea-8af0-c238e6fa2d58.png)

2020-02-14 04:51 UTC, Jigar3 commented
White looks to dull and also the preloader isn't that great in terms of look and feel. Try using some other preloader

2020-02-14 05:00 UTC, sggts04 commented
@Jigar3 new preloader up :|
Shift + F5 the live link

2020-02-14 05:02 UTC, Jigar3 commented
still looks dull

2020-02-14 05:52 UTC, sggts04 commented
@Jigar3 now?

2020-02-14 08:05 UTC, Jigar3 requested changes

2020-02-14 08:05 UTC, Jigar3 commented on index.html
> +        $(".se-pre-con").delay(1000).fadeOut("slow");
why are you adding a delay. It is for something specific

2020-02-14 08:09 UTC, sggts04 commented
@Jigar3 removed the delay

2020-02-14 08:22 UTC, Jigar3 commented
squash your commits

2020-02-14 09:40 UTC, sggts04 commented
@Jigar3 done

2020-02-14 11:38 UTC, thesmallstar commented
@sggts04 can you remove conflicts?

2020-02-14 11:39 UTC, sggts04 commented
@thesmallstar resolved

2020-02-14 15:51 UTC, sggts04 commented
@thesmallstar pls review

2020-02-14 18:09 UTC, NitinMadhukar commented
@sggts04 squash commits

2020-02-14 18:58 UTC, sggts04 commented
@NitinMadhukar done

2020-02-15 02:56 UTC, sggts04 commented
@Jigar3 @thesmallstar please review

2020-02-15 04:16 UTC, merged